### ISSUE TITLE
Marking a discussion off-topic fails to create the new topic

### ISSUE THREAD

**Issue by ewinslow** [Elgg/www.elgg.org#52] opened 2015-08-07 20:32 UTC
I clicked "off topic", typed a new title, and submitted the form.

Expected result is that the new discussion would be created and I'd be perhaps forwarded there or kept on the same page I was already on.

I got forwarded to the elgg.org homepage instead. The topic seems not to have been created.

The original off-topic comment *was* correctly modified to be marked as off-topic.

**Comment by juho-jaakkola** [comment] 2015-09-13 10:20
Closing because I cannot reproduce the problem.

**Closed by juho-jaakkola** 2015-09-13 10:20 UTC
Labels: bug
